// Random C++ code generated by AI Assistant

#include <iostream>
#include <string>
#include <vector>

using namespace std;

int main() {
    vector<string> names = {"John", "Jane", "Bob"};
    string name;

    cout << "Enter your name: ";
    cin >> name;

    if (names.contains(name)) {
        cout << "Hello, " << name << "!" << endl;
    } else {
        cout << "I don't know you." << endl;
    }

    return 0;
}
